name: Check with Pylint and deploy

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      PAYPAL_API_USERNAME: ${{ secrets.PAYPAL_API_USERNAME }}
      PAYPAL_API_PASSWORD: ${{ secrets.PAYPAL_API_PASSWORD }}
      PAYPAL_API_SIGNATURE: ${{ secrets.PAYPAL_API_SIGNATURE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          pylint shop_api store