name: Check with Pylint and deploy

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      PAYPAL_API_USERNAME: ${{ secrets.PAYPAL_API_USERNAME }}
      PAYPAL_API_PASSWORD: ${{ secrets.PAYPAL_API_PASSWORD }}
      PAYPAL_API_SIGNATURE: ${{ secrets.PAYPAL_API_SIGNATURE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          pylint shop_api store

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      PAYPAL_API_USERNAME: ${{ secrets.PAYPAL_API_USERNAME }}
      PAYPAL_API_PASSWORD: ${{ secrets.PAYPAL_API_PASSWORD }}
      PAYPAL_API_SIGNATURE: ${{ secrets.PAYPAL_API_SIGNATURE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest shop_api/tests

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy on PythonAnywhere
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/ \
            -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
            -d "executable=/bin/bash&command=/home/${{ secrets.PA_USERNAME }}/deploy.sh"

      - name: Reload web app
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_USERNAME }}.pythonanywhere.com/reload/ \
            -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"